In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm
import pickle

In [2]:
DATADIR = "/home/trojan/Desktop/dimentia/data_10slices/dataset with PGGAN/train"

CATEGORIES = ["AD", "CN"]

In [3]:
IMG_SIZE = 28
training_data = []

def create_training_data():
    for category in CATEGORIES:  # do dogs and cats

        path = os.path.join(DATADIR,category)  # create path to dogs and cats
        class_num = CATEGORIES.index(category)  # get the classification  (0 or a 1). 0=dog 1=cat

        for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                new_array = cv2.normalize(new_array , None, 0, 1, cv2.NORM_MINMAX)
                new_array = new_array.astype("float32")
                training_data.append([new_array, class_num])  # add this to our training_data
            except Exception as e:  # in the interest in keeping the output clean...
                pass
            
create_training_data()

print(len(training_data))

100%|██████████| 9839/9839 [00:11<00:00, 869.47it/s]

19677


In [4]:
import random

random.shuffle(training_data)

In [5]:
for sample in training_data[:10]:
    print(sample[1])

1
0
1
1
0
0
1
1
0
1


In [6]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)
    
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1) # IMG_SIZE, IMG_SIZE, 1
y = np.array(y)

In [7]:
X.shape

(19677, 28, 28, 1)

In [8]:
X.dtype

dtype('float32')

In [9]:
pickle_out = open("/home/trojan/Desktop/dimentia/CapsNet/X.pickle", "wb")
pickle.dump(X, pickle_out, protocol=pickle.HIGHEST_PROTOCOL)
pickle_out.close()

pickle_out = open("/home/trojan/Desktop/dimentia/CapsNet/y.pickle", "wb")
pickle.dump(y, pickle_out, protocol=pickle.HIGHEST_PROTOCOL)
pickle_out.close()

In [10]:
pickle_in = open("/home/trojan/Desktop/dimentia/CapsNet/X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("/home/trojan/Desktop/dimentia/CapsNet/y.pickle","rb")
y = pickle.load(pickle_in)


In [11]:
print(X.dtype)
print(y.dtype)

float32
int64


In [12]:
print(X[0])

[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [